name: eratosthenes
channels:
  - conda-forge
dependencies:
  - python=3.8
  - gcsfs
  - geopandas
  - gdal
  - ipywidgets
  - jupyterlab
  - pystac-client 
  - rioxarray
  - shapely 
  - pip
  - pip:
      - s2cloudless
      - sentinelsat
      - stac2dcache
      - stactools 
      - git+https://github.com/stactools-packages/sentinel2
      - git+https://github.com/GO-Eratosthenes/morphsnakes@albedo-included
      - git+https://github.com/GO-Eratosthenes/dhdt
